services:
  db:
    image: mysql:8.0
    container_name: eco_travel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eco_travel_api
    ports:
      - "3307:3306" 

  php:
    build: .
    container_name: eco_travel_php
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public